version: '{build}'
os: Visual Studio 2015

platform: x64

environment:
  PYTHON3: "C:\\Python36"
  PIP3: C:\\Python36\Scripts\pip
  
init:
  - cmd: set PATH=%PYTHON3%;%PYTHON3%\scripts;%PATH%

install:
  - pip --version
  - pip install meson ninja
  - where meson
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - where meson

build: off
