version: '{build}'
os: Visual Studio 2015

platform: x64

environment:
  PYTHON3: "C:\\Python36"
  PIP3: C:\\Python36\Scripts\pip
  
init:
  - cmd: set PATH=%PYTHON3%;%PYTHON3%\scripts;%PATH%

install:
  - ps: choco install -y -r pkgconfiglite
  - git clone https://github.com/ishmael1985/gstreamer-media-SDK.git
  - cd gstreamer-media-SDK
  - pip install meson ninja
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - meson ../msdk_build

build: off
