version: '{build}'
os: Visual Studio 2015

platform: x64

install:
  - dir C:\Python36-x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - python3 --version

build: off
