version: '{build}'
os: Visual Studio 2015

platform: x64

compiler: msvc2015

msys2_arch: x86_64
msys2_dir: msys64
msystem: MINGW64
buildtool: msbuild

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - set
  - where cl.exe

build: off
