version: '{build}'
os: Visual Studio 2015

platform: x64

environment:
  PYTHON3: "C:\\Python36"
  PIP3: C:\\Python36\Scripts\pip
  
init:
  - cmd: set PATH=%PYTHON3%;%PYTHON3%\scripts;%PATH%

install:
  - ps: choco install -y -r pkgconfiglite
  - ps: Start-FileDownload 'https://gstreamer.freedesktop.org/data/pkg/windows/1.12.3/gstreamer-1.0-devel-x86_64-1.12.3.msi'
  - msiexec /i "gstreamer-1.0-devel-x86_64-1.12.3.msi"
  - git clone https://github.com/ishmael1985/gstreamer-media-SDK.git
  - cd gstreamer-media-SDK
  - pip install meson ninja
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - set PKG_CONFIG_PATH=%GSTREAMER_1_0_ROOT_X86_64%lib\pkgconfig
  - set
  - meson ../msdk_build

build: off
